image: docker:latest

services:
  - docker:dind

stages:
  - build

before_script:
  # Login to Google Container Registry
  - base64 -d $GCP_SA_KEY | docker login -u _json_key --password-stdin https://gcr.io

build:
  stage: build
  script:
    - echo $FIRESTORE_AUTH | base64 -d > ${CI_PROJECT_DIR}/serviceAccountKey.json
    - echo $HASH_SECRET | base64 -d > ${CI_PROJECT_DIR}/internal/webserver/utility/hash_util/secret.go
    # Build and tag image for both GCR and Gitlab registries
    - docker build --cache-from -t gcr.io/$GCP_PROJECT_ID/covid_api:latest .
    # Push image to GCR
    - docker push gcr.io/$GCP_PROJECT_ID/covid_api:latest