image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/namespace/project
  DOCKER_HUB_LINK: https://index.docker.io/v1/
  GOOGLE_PROJECT_ID: cloud2005-assignment-2
  IMAGE_NAME: rest-covid-api

stages:
  - test
  - build

before_script:
  - mkdir -p "$GOPATH/src/$(dirname $REPO_NAME)"
  - ln -svf "$CI_PROJECT_DIR" "$GOPATH/src/$REPO_NAME"
  - cd "$GOPATH/src/$REPO_NAME"
  - echo $FIRESTORE_AUTH | base64 -d > $GOPATH/src/$REPO_NAME/serviceAccountKey.json
  - echo $HASH_SECRET | base64 -d > $GOPATH/src/$REPO_NAME/internal/webserver/utility/hash_util/secret.go

test:
  stage: test
  script:
    - go test ./...

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo $FIRESTORE_AUTH | base64 -d > ${CI_PROJECT_DIR}/serviceAccountKey.json
    - echo $HASH_SECRET | base64 -d > ${CI_PROJECT_DIR}/internal/webserver/utility/hash_util/secret.go
    - echo "{\"auths\":{\"$DOCKER_HUB_LINK\":{\"auth\":\"$(echo -n vfaergestad:${DOCKER_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "vfaergestad/$IMAGE_NAME:latest"
      --force

    - echo $GCP_SA_KEY | base64 -d
    - echo $GCP_SA_KEY | base64 -d > /kaniko/kaniko-secret.json
    - /kaniko/executor 
      --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/Dockerfile 
      --destination gcr.io/$GOOGLE_PROJECT_ID/$IMAGE_NAME:latest
      -- force