# https://colinwilson.uk/2020/07/10/configure-gitlab-ci-with-google-container-registry/

image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  image: google/cloud-sdk
  stage: build
  script:
    - echo $GCP_SA_KEY | base64 -d > gcloud-service-key.json
    - echo $FIRESTORE_AUTH | base64 -d > ${CI_PROJECT_DIR}/serviceAccountKey.json
    - echo $HASH_SECRET | base64 -d > ${CI_PROJECT_DIR}/internal/webserver/utility/hash_util/secret.go
    - gcloud auth activate-service-account --key-file gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    # Build and tag image for both GCR and Gitlab registries
    - docker build . -t gcr.io/$GCP_PROJECT_ID/covid-api:latest
    # Push image to GCR
    - docker push gcr.io/$GCP_PROJECT_ID/covid-api:latest