version: "3"
services:
  app:
    container_name: covid-api
    image: covid-api:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8080"
    restart: unless-stopped